In [1]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
import os
import rasterio
from osgeo import gdal
from tifffile import imsave
%matplotlib inline
import cv2

In [2]:
#path2 = r"C:\Users\Quint\Documents\EPA\Thesis\ENC_Py3_mra-main\amsterdam_metronamica-main\raster_comparison\mmr_rasters\mmr_rasters_12_7"

import rasterio as rio
path_suit = r'EU_data\\mmr_2\\data\\suitability\\mmr_suit_DEM_Q2.tif'
with rio.open(path_suit) as dem_src:
    suit_dem = dem_src.read(1)


In [3]:
luc_DEM=gdal.Open(path_suit)
projection = luc_DEM.GetProjection()
geotransform= luc_DEM.GetGeoTransform()

In [5]:
geotransform

(258823.0, 200.0, 0.0, 2162453.0, 0.0, -200.0)

In [10]:
copy_1=geotransform

In [9]:
geotrans_2=(259023.0 , 200.0,0.0,2162253.0,0.0,-200.0) 

In [34]:
suit_dem

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ..., 239, 245, 233],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=int16)

In [35]:
a=np.delete(suit_dem, 0, 0)
b=np.delete(a, 0, 1)

In [36]:
b.shape

(506, 398)

In [37]:
outputPath = r'EU_data/mmr_2/data/suitability/mmr_suit_DEM_Q3.tif'
cv2.imwrite(outputPath, b)
dataset2 = gdal.Open(outputPath, gdal.GA_Update)
dataset2.SetGeoTransform(geotrans_2)
dataset2.SetProjection(projection)

0

In [14]:
#path2 = r"C:\Users\Quint\Documents\EPA\Thesis\ENC_Py3_mra-main\amsterdam_metronamica-main\raster_comparison\mmr_rasters\mmr_rasters_12_7"

import rasterio as rio
path_suit = r'EU_data\\mmr_2\\data\\suitability\\mmr_suit_slope3.tif'
with rio.open(path_suit) as dem_src:
    suit_slope = dem_src.read(1)


In [15]:
a=np.delete(suit_slope, 0, 0)
b=np.delete(a, 0, 1)

In [16]:
b[b <0] = 0

In [17]:
outputPath = r'EU_data/mmr_2/data/suitability/mmr_suit_slope_Q3.tif'
cv2.imwrite(outputPath, b)
dataset2 = gdal.Open(outputPath, gdal.GA_Update)
dataset2.SetGeoTransform(geotrans_2)
dataset2.SetProjection(projection)

0

In [18]:
#path2 = r"C:\Users\Quint\Documents\EPA\Thesis\ENC_Py3_mra-main\amsterdam_metronamica-main\raster_comparison\mmr_rasters\mmr_rasters_12_7"

import rasterio as rio
path_suit = r'EU_data\\mmr_2\\data\\suitability\\mmr_soil4.tif'
with rio.open(path_suit) as dem_src:
    suit_soil = dem_src.read(1)


In [19]:
a=np.delete(suit_soil, -1, 0)
b=np.delete(a, 0, 1)

In [20]:
outputPath = r'EU_data/mmr_2/data/suitability/mmr_soil_Q3.tif'
cv2.imwrite(outputPath, b)
dataset2 = gdal.Open(outputPath, gdal.GA_Update)
dataset2.SetGeoTransform(geotrans_2)
dataset2.SetProjection(projection)

0

In [32]:
#path2 = r"C:\Users\Quint\Documents\EPA\Thesis\ENC_Py3_mra-main\amsterdam_metronamica-main\raster_comparison\mmr_rasters\mmr_rasters_12_7"

import rasterio as rio
path_2016 = r'EU_data/mmr_2/mmr_land/mmr_2016_rw.tif'
with rio.open(path_2016) as dem_src:
    luc_2016 = dem_src.read(1)


In [33]:
np.unique(luc_2016)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=uint8)

In [34]:
a=np.delete(luc_2016, 0, 0)
b=np.delete(a, 0, 1)

In [35]:
outputPath = r'EU_data/mmr_2/mmr_land/mmr_landuse_2016_final.tif'
cv2.imwrite(outputPath, b)
dataset2 = gdal.Open(outputPath, gdal.GA_Update)
dataset2.SetGeoTransform(geotrans_2)
dataset2.SetProjection(projection)

0

In [21]:
#path2 = r"C:\Users\Quint\Documents\EPA\Thesis\ENC_Py3_mra-main\amsterdam_metronamica-main\raster_comparison\mmr_rasters\mmr_rasters_12_7"

import rasterio as rio
path_2016 = r'EU_data/mmr_2/mmr_land/mmr_landuse_2016_final8.tif'
with rio.open(path_2016) as dem_src:
    luc_2016 = dem_src.read(1)


In [22]:
np.unique(luc_2016)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=uint8)

In [23]:
a=np.delete(luc_2016, -1, 0)
b=np.delete(a, 0, 1)

In [26]:
outputPath = r'EU_data/mmr_2/mmr_land/mmr_landuse_2016_final9.tif'
cv2.imwrite(outputPath, b)
dataset2 = gdal.Open(outputPath, gdal.GA_Update)
dataset2.SetGeoTransform(geotrans_2)
dataset2.SetProjection(projection)

0